project_id = "xcevckeqhcanbyhqatcq"

[functions.sitemap]
verify_jwt = false

[functions.admin-create-post]
verify_jwt = false

[functions.subscribe-beehiiv]
verify_jwt = false

[functions.content-machine-generate]
verify_jwt = false

[functions.content-machine-publish]
verify_jwt = false

[functions.cost-estimate]
verify_jwt = false

[functions.admin-faqs]
verify_jwt = false
